version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HISTFILE: "/app/tmp/.bash_history"
    tty: true
    volumes:
      - .:/app
      - bundle:/app/vendor/bundle

volumes:
  bundle:
    driver: local
